
num_actions: 29
dof_config:
  isaac_order:
  - left_shoulder_pitch_joint
  - right_shoulder_pitch_joint
  - waist_pitch_joint
  - left_shoulder_roll_joint
  - right_shoulder_roll_joint
  - waist_roll_joint
  - left_shoulder_yaw_joint
  - right_shoulder_yaw_joint
  - waist_yaw_joint
  - left_elbow_joint
  - right_elbow_joint
  - left_hip_pitch_joint
  - right_hip_pitch_joint
  - left_wrist_roll_joint
  - right_wrist_roll_joint
  - left_hip_roll_joint
  - right_hip_roll_joint
  - left_wrist_pitch_joint
  - right_wrist_pitch_joint
  - left_hip_yaw_joint
  - right_hip_yaw_joint
  - left_wrist_yaw_joint
  - right_wrist_yaw_joint
  - left_knee_joint
  - right_knee_joint
  - left_ankle_pitch_joint
  - right_ankle_pitch_joint
  - left_ankle_roll_joint
  - right_ankle_roll_joint
  left_shoulder_pitch_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.2
    joint_signs: 1.0
    torque_limits: 25.0
  right_shoulder_pitch_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.2
    joint_signs: 1.0
    torque_limits: 25.0
  waist_pitch_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: -1.0
    torque_limits: 50.0
  left_shoulder_roll_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.2
    joint_signs: 1.0
    torque_limits: 25.0
  right_shoulder_roll_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: -0.2
    joint_signs: 1.0
    torque_limits: 25.0
  waist_roll_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: -1.0
    torque_limits: 50.0
  left_shoulder_yaw_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 25.0
  right_shoulder_yaw_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 25.0
  waist_yaw_joint:
    kp: 40.179237
    kd: 2.55789
    action_scale: 0.547546
    default_pos: 0.0
    joint_signs: -1.0
    torque_limits: 88.0
  left_elbow_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.6
    joint_signs: 1.0
    torque_limits: 25.0
  right_elbow_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.6
    joint_signs: 1.0
    torque_limits: 25.0
  left_hip_pitch_joint:
    kp: 40.179237
    kd: 2.55789
    action_scale: 0.547546
    default_pos: -0.312
    joint_signs: 1.0
    torque_limits: 88.0
  right_hip_pitch_joint:
    kp: 40.179237
    kd: 2.55789
    action_scale: 0.547546
    default_pos: -0.312
    joint_signs: 1.0
    torque_limits: 88.0
  left_wrist_roll_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 25.0
  right_wrist_roll_joint:
    kp: 14.250623
    kd: 0.907223
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 25.0
  left_hip_roll_joint:
    kp: 99.098427
    kd: 6.308802
    action_scale: 0.350661
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 88.0
  right_hip_roll_joint:
    kp: 99.098427
    kd: 6.308802
    action_scale: 0.350661
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 88.0
  left_wrist_pitch_joint:
    kp: 16.778328
    kd: 1.068141
    action_scale: 0.074501
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 5.0
  right_wrist_pitch_joint:
    kp: 16.778328
    kd: 1.068141
    action_scale: 0.074501
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 5.0
  left_hip_yaw_joint:
    kp: 40.179237
    kd: 2.55789
    action_scale: 0.547546
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 88.0
  right_hip_yaw_joint:
    kp: 40.179237
    kd: 2.55789
    action_scale: 0.547546
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 88.0
  left_wrist_yaw_joint:
    kp: 16.778328
    kd: 1.068141
    action_scale: 0.074501
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 5.0
  right_wrist_yaw_joint:
    kp: 16.778328
    kd: 1.068141
    action_scale: 0.074501
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 5.0
  left_knee_joint:
    kp: 99.098427
    kd: 6.308802
    action_scale: 0.350661
    default_pos: 0.669
    joint_signs: 1.0
    torque_limits: 139.0
  right_knee_joint:
    kp: 99.098427
    kd: 6.308802
    action_scale: 0.350661
    default_pos: 0.669
    joint_signs: 1.0
    torque_limits: 139.0
  left_ankle_pitch_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: -0.363
    joint_signs: 1.0
    torque_limits: 50.0
  right_ankle_pitch_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: -0.363
    joint_signs: 1.0
    torque_limits: 50.0
  left_ankle_roll_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 50.0
  right_ankle_roll_joint:
    kp: 28.501245
    kd: 1.814446
    action_scale: 0.438577
    default_pos: 0.0
    joint_signs: 1.0
    torque_limits: 50.0



obs_config:
  sensors:
    base_ang_vel:
      shape:
      - 3
      obs_scale: 0.25
      frames: 8
      stride: 1
    projected_gravity:
      shape:
      - 3
      obs_scale: 1.0
      frames: 8
      stride: 1
    velocity_commands:
      shape:
      - 3
      obs_scale: 1.0
      frames: 8
      stride: 1
    joint_pos:
      shape:
      - 29
      obs_scale: 1.0
      frames: 8
      stride: 1
    joint_vel:
      shape:
      - 29
      obs_scale: 0.05
      frames: 8
      stride: 1
    actions:
      shape:
      - 29
      obs_scale: 1.0
      frames: 8
      stride: 1
    depth:
      shape:
      - 18
      - 32
      obs_scale: 1.0
      frames: 8
      stride: 5
  proprio_obs:
    sources:
    - base_ang_vel
    - projected_gravity
    - velocity_commands
    - joint_pos
    - joint_vel
    - actions
    history_len: 1
    tail_ndim: 0
    history_mode: merge
  enc_input:
    sources:
    - depth
    history_len: 1
    tail_ndim: 2
    history_mode: merge
deploy_obs_heads:
- enc_input
- proprio_obs
pd_rate: 200.0
infer_rate: 50.
clip_actions: 1000.0
clip_obs: 1000.
exp_avg_decay: 1.0
